name: clean_architecture
description: A project to build a clean architecture.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0
  retrofit: ^4.0.1
  get_it: ^7.2.0
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^0.5.5
  json_annotation: ^4.8.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

